services:
  - type: web
    name: maratona-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "python render_start.py"
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: RENDER
        value: "true"
