# Generated by Django 5.2.5 on 2025-08-20 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscricao', models.CharField(editable=False, max_length=10, unique=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)], verbose_name='Idade')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('categoria', models.CharField(choices=[('M_15_29', 'Masculino 15 a 29 anos'), ('M_30_39', 'Masculino 30 a 39 anos'), ('M_40_49', 'Masculino 40 a 49 anos'), ('M_50_PLUS', 'Masculino acima de 50 anos'), ('F_15_30', 'Mulheres 15 a 30 anos'), ('F_32_PLUS', 'Mulheres acima de 32 anos'), ('VISITANTES', 'Categoria Geral Visitantes')], max_length=20, verbose_name='Categoria')),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status do Pagamento')),
                ('mercado_pago_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('valor_inscricao', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['numero_inscricao'],
            },
        ),
    ]
