# Generated by Django 5.2.5 on 2025-08-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='rg',
            field=models.CharField(default='00.000.000-0', max_length=20, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='valor_inscricao',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
