# Generated by Django 5.2.5 on 2025-08-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_inscricao_cpf_inscricao_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='valor_inscricao',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10),
        ),
    ]
